name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - uses: brightdigit/swift-build@v1
        with:
          scheme: KSwitch
          use-xcbeautify: true
          xcbeautify-renderer: github-actions
